fix: block flush tasks from running simultaneously
Parsely/parsely-android pull request #66
Opened 2023-09-11 14:44 UTC by wzieba

Closes: #65 

By introducing `flushInProgress` flag, we limit the possibility of executing multiple FlushQueue AsyncTasks simultaneously, which could result in sending the same payload multiple times.

2023-09-12 08:58 UTC, ParaskP7 requested changes
👋 @wzieba !

I have reviewed and tested this PR as per the instructions, it didn't works as expected, please check my blocker (🚫) comment! 🤔 

-----

Furthermore, I wonder if introducing yet another state (`flushInProgress`) here is the best we could do, and more so, if that wouldn't introduce some kind of another bug (can't think of any, that is, out of the top of my head, but still). Wdyt? 🤔

What worries me is if there are other valid scenarios where `flushEventQueue()` needs to be triggered twice (or more), while the previous `doInBackground(...)` is still in-progress. Again, can't think of anything, and I just want to open this discussion now so that you could maybe investigate this and make sure that we are 100% sure that as we are fixing a potential bug, we are not introducing another regression of some kind. 🤔

Also, I wonder why the designers of `ParselyTracker.java` didn't think about that case, guarding against multiple `flushEventQueue()` calls, as it seems pretty easy to do. Maybe they did, but decided against it, maybe not. Or maybe, they didn't think of that because trying multiple `flushEventQueue()` calls, the way we tested it, via the `FLUSH EVENT QUEUE` is something that can't/shouldn't be done manually in production apps using our SKD, and instead, only depend on the timer to only do that automatically, based on the `flushInterval` parameter, after a specific period of time. 🤔

Me keep writing and thinking about it, I wonder whether it would make more sense to somehow limit the `flushEventQueue()` to be an internal or private method, only accessed by the timer (see `FlushManager.runningTask`), and also, maybe even limit the `flushInterval` to a minimum allowed. For example, currently, entering a value of `0` seconds is allowed, but this would cause an `IllegalArgumentException` exception for a `Non-positive period.`, but maybe we should even disallow/overwrite `0-4` seconds, setting the minimum to `5` in order to avoid sequential flushes very close to each other.

Apologies if all the above are not helping or even irrelevant, just wanted to share as much of my thoughts here just in case they could help you move forward. 😊

2023-09-12 08:58 UTC, ParaskP7 commented on parsely/src/main/java/com/parsely/parselyandroid/ParselyTracker.java
> +        if (!flushInProgress) {
Blocker (🚫): Unfortunately, this wouldn't work as is (tested too). What you need is to set `flushInProgress` to `true` right after this `if (!flushInProgress)` check and remove the `flushInProgress = true;` at the beginning of `doInBackground(...)` (not needed), only leaving the `flushInProgress = false;` at the end.

2023-09-12 09:27 UTC, wzieba commented
Thanks @ParaskP7 , you raise good concerns in the comment and I agree with them 👍. I can provide some more context:

> What worries me is if there are other valid scenarios where flushEventQueue() needs to be triggered twice (or more), while the previous doInBackground(...) is still in-progress.

There's no *valid* scenario to call `flushEventQueue()` twice. The scenario I thought to cover with this fix was an invalid configuration of the SDK by users of it. 

> (...) the way we tested it, via the FLUSH EVENT QUEUE is something that can't/shouldn't be done manually in production apps using our SKD, and instead, only depend on the timer to only do that automatically, based on the flushInterval parameter, after a specific period of time.

Users are asked to call `flushEventQueue` in `onDestroy` of the Activity ([details](https://docs.parse.ly/android-sdk/#h-using-the-sdk)). So, with current interface, we have to offer `flushEventQueue`. Although I have concerns with this approach - making http request in the `onDestroy` will usually (if not always) fail, as it's already too late for this in app's lifecycle. But this is maybe a separate topic to discuss in P2.

> Me keep writing and thinking about it, I wonder whether it would make more sense to somehow limit the flushEventQueue() to be an internal or private method, only accessed by the timer (see FlushManager.runningTask), and also, maybe even limit the flushInterval to a minimum allowed.

Yes, it'd be the best strategy IMO as well. I'll prepare a P2 proposal and then we can discuss it with the rest of the team 👍 

---

Thanks for sharing your thoughts @ParaskP7 , it made me rethink the approach proposed here! I'll put this PR on draft for now.

2023-09-12 09:52 UTC, ParaskP7 commented
> Thanks @ParaskP7 , you raise good concerns in the comment and I agree with them 👍. I can provide some more context:

Thank YOU @wzieba ! 🥇 

> There's no valid scenario to call flushEventQueue() twice. The scenario I thought to cover with this fix was an invalid configuration of the SDK by users of it.

Got it, thanks! 👍 

> Users are asked to call flushEventQueue in onDestroy of the Activity ([details](https://docs.parse.ly/android-sdk/#h-using-the-sdk)). So, with current interface, we have to offer flushEventQueue.

True... 🤷 

> Although I have concerns with this approach - making http request in the onDestroy will usually (if not always) fail, as it's already too late for this in app's lifecycle. But this is maybe a separate topic to discuss in P2.

Right, totally a separate topic for discussion, I agree! 👍 

> Yes, it'd be the best strategy IMO as well. I'll prepare a P2 proposal and then we can discuss it with the rest of the team 👍

Awesome, thanks! 🙇 

> Thanks for sharing your thoughts @ParaskP7 , it made me rethink the approach proposed here! I'll put this PR on draft for now.

Ah, I didn't want to block your work, apologies, this wasn't my intention here. Please think about it a bit and feel free to ask for my review when you are ready with another solution. 🙏

2023-10-16 11:03 UTC, wzieba commented
Obsolete by #77

2023-10-16 11:03 UTC, closed without merging